enum BridgeTypes {
    NORTH_BRIDGE_ONE,
    NORTH_BRIDGE_TWO,
    NORTH_BRIDGE_THREE,
    SOUTH_BRIDGE_FOUR,
    SOUTH_BRIDGE_FIVE,
    SOUTH_BRIDGE_SIX;
}

enum KnobSetTypes {
    NORTH_KNOBSET_ONE,
    NORTH_KNOBSET_TWO,
    NORTH_KNOBSET_THREE,
    SOUTH_KNOBSET_FOUR,
    SOUTH_KNOBSET_FIVE,
    SOUTH_KNOBSET_SIX;
}

enum CoversTypes {
    NORTH_COVERS_ONE,
    NORTH_COVERS_TWO,
    NORTH_COVERS_THREE,
    SOUTH_COVERS_FOUR,
    SOUTH_COVERS_FIVE,
    SOUTH_COVERS_SIX;
}

enum NeckTypes {
    NORTH_NECK_ONE,
    NORTH_NECK_TWO,
    NORTH_NECK_THREE,
    SOUTH_NECK_FOUR,
    SOUTH_NECK_FIVE,
    SOUTH_NECK_SIX;
}

enum PickGuardTypes {
    NORTH_PICKGUARD_ONE,
    NORTH_PICKGUARD_TWO,
    NORTH_PICKGUARD_THREE,
    SOUTH_PICKGUARD_FOUR,
    SOUTH_PICKGUARD_FIVE,
    SOUTH_PICKGUARD_SIX;
}

enum PickUpsTypes {
    NORTH_PICKUPS_ONE,
    NORTH_PICKUPS_TWO,
    NORTH_PICKUPS_THREE,
    SOUTH_PICKUPS_FOUR,
    SOUTH_PICKUPS_FIVE,
    SOUTH_PICKUPS_SIX;
}


